import { Category, Product } from '../../types/store';
// Generated by vite-plugins/activeClientConfig.ts: resolves to only this
// deployment's own demo catalog — Shams's fully separate dataset, or the
// shared voltix/apex/lumina one — never all of them at once.
import { ACTIVE_PRODUCTS, ACTIVE_CATEGORIES } from 'virtual:active-demo-catalog';

// Per-client demo catalog lookup. Shams ships its own fully separate demo
// dataset (src/data/demo/shams/*) rather than sharing the Gulf-clients'
// PRODUCTS/CATEGORIES arrays in mockData.ts — the two catalogs must never mix,
// and (per the active-demo-catalog plugin) never even reach the same bundle.
export function getDemoProductsForClient(clientId: string): Product[] {
  if (clientId === 'shams') return ACTIVE_PRODUCTS;
  return ACTIVE_PRODUCTS.filter((p) => p.storeId === clientId);
}

export function getDemoCategoriesForClient(_clientId: string): Category[] {
  return ACTIVE_CATEGORIES;
}
