import { ClientConfig, parseClientConfig } from './clients/schema';
import { CLIENT_IDS } from './clients/clientIds';
// Generated by vite-plugins/activeClientConfig.ts: resolves to a module that
// re-exports ONLY this deployment's own client config — never all four. This
// is what keeps one client's bundle free of every other client's brand
// names, currencies, and market copy.
import { activeClientConfig as rawConfig } from 'virtual:active-client-config';

function resolveActiveClient(): ClientConfig {
  const storeId = import.meta.env.VITE_STORE_ID as string | undefined;

  if (!storeId || !storeId.trim()) {
    throw new Error(
      `Missing VITE_STORE_ID environment variable.\n\n` +
        `This storefront is a white-label template: exactly one client must be selected ` +
        `at build/run time. Set VITE_STORE_ID to one of: ${CLIENT_IDS.join(', ')}.\n\n` +
        `Example: VITE_STORE_ID=voltix npm run dev`
    );
  }

  if (!(CLIENT_IDS as readonly string[]).includes(storeId) || rawConfig === undefined) {
    throw new Error(
      `Unknown VITE_STORE_ID "${storeId}".\n\n` +
        `Available clients: ${CLIENT_IDS.join(', ')}. ` +
        `There is no fallback client — fix VITE_STORE_ID before building or running the storefront.`
    );
  }

  return parseClientConfig(rawConfig, `${storeId}.config.ts`);
}

// Resolved once per session/build. The active client identity is fixed for
// the lifetime of this deployment — it must never change based on user
// input, URL parameters, or runtime UI state.
export const activeClient: ClientConfig = resolveActiveClient();
